#!/usr/bin/env python3
"""Generate an `App`-adapter for a user-supplied script.

The worker executor only imports files that define `class App` with
`__init__(params)`, `start()`, and `step()`. Most existing Python scripts
in this repo use `def main()` or `if __name__ == "__main__":`. This tool
emits a ready-to-upload adapter that wraps such a script via `subprocess`.

Two modes are supported:

  (1) One-file script (default)
        Produces `<basename>_app.py` next to the input. The adapter builds
        an `argv` from the parameters and `subprocess.Popen`s the script
        in `cwd=/app/workspace` so its output reaches the worker log.

  (2) Chunked script (--chunk)
        Splits the script into N parts no larger than `--chunk-size`
        bytes (default 7500) and emits `<basename>_app.py` that
        reassembles them on the worker side. Useful when the worker
        upload endpoint drops multipart requests on files > 10KB.

Example:
    python app_scaffold.py tmp/orbit_earth.py \
        --name orbit_earth_app \
        --param grid:str=skynet-scout2 \
        --param center_distance_km:float=90 \
        --flag max_laps:int=0 \
        --flag duration_sec:int=0

The generated file is fully functional but you should review the
`build_argv()` helper and the `start()`/`step()` bodies; the scaffold
makes conservative choices that fit ~80% of cases.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Optional


WORKER_CWD = "/app/workspace"


ADAPTER_TEMPLATE = '''"""Auto-generated App adapter for {entry_basename}.

Generated by: docs/agent-skills/gaming/se-worker-control/scripts/app_scaffold.py
Adjust `build_argv()` if your script takes other arguments, and extend
`start()` to do any one-time initialization your script cannot do
via command-line flags.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import threading
from pathlib import Path
from typing import Any, Dict, List, Optional


CHUNKS: List[str] = {chunks_repr}
SCRIPT_NAME = "{entry_basename}"
WORKSPACE = Path("{worker_cwd}")


def assemble() -> Path:
    """Reassemble the chunks back into one executable file.

    Each chunk declares `_part_<i> = "<original text>"` via repr(). We
    exec() the chunk files in a fresh namespace and concatenate the
    string constants in order.
    """
    target = WORKSPACE / SCRIPT_NAME
    namespace: Dict[str, Any] = {{}}
    for name in CHUNKS:
        p = WORKSPACE / name
        if not p.exists():
            raise FileNotFoundError(f"chunk missing on worker: {{p}}")
        exec(p.read_text(encoding="utf-8"), namespace)
    parts = [str(namespace[f"_part_{{i}}"]) for i in range(1, len(CHUNKS) + 1)]
    target.write_text("".join(parts), encoding="utf-8")
    print(f"[adapter] assembled {{target}} from {{len(CHUNKS)}} chunk(s)", flush=True)
    return target


def build_argv(params: Dict[str, Any]) -> List[str]:
    """Translate WORKER_PARAMS into argv for the wrapped script.

    Anything you don't want to forward (e.g. grid_id auto-injected by
    the executor) is stripped here.
    """
    argv: List[str] = [str(WORKSPACE / SCRIPT_NAME)]
{build_argv_body}
    return argv


class App:
    def __init__(self, params: Dict[str, Any]):
        self.params = dict(params)
        print(f"[adapter] params: {{json.dumps(self.params, ensure_ascii=False)}}", flush=True)
        self._proc: Optional[subprocess.Popen] = None
        self._lock = threading.Lock()

    def start(self) -> None:
        target = assemble()
        argv = build_argv(self.params)
        print(f"[adapter] launching: {{' '.join(argv)}}", flush=True)
        env = os.environ.copy()
        with self._lock:
            self._proc = subprocess.Popen(
                [sys.executable, "-u", str(target), *argv[1:]],
                cwd=str(WORKSPACE),
                stdout=sys.stdout,
                stderr=subprocess.STDOUT,
                env=env,
            )

    def step(self) -> None:
        with self._lock:
            proc = self._proc
        if proc is None:
            print("[adapter] step() before start()", flush=True)
            return
        rc = proc.poll()
        if rc is None:
            print(f"[adapter] running pid={{proc.pid}}", flush=True)
        else:
            print(f"[adapter] exited rc={{rc}}", flush=True)


if __name__ == "__main__":
    # local smoke test
    app = App({{"_dummy": True}})
    app.start()
    while True:
        app.step()
        import time as _t
        _t.sleep(1.0)
'''


def _coerce(value: str, kind: str):
    if kind == "int":
        return int(value)
    if kind == "float":
        return float(value)
    if kind == "bool":
        return value.lower() in ("1", "true", "yes", "on")
    return value


def parse_param(spec: str) -> tuple[str, str, object]:
    """Parse `--param NAME:TYPE=VALUE`."""
    if "=" not in spec:
        raise ValueError(f"bad --param {spec!r}: expected NAME:TYPE=VALUE")
    name_kind, value = spec.split("=", 1)
    if ":" not in name_kind:
        raise ValueError(f"bad --param {spec!r}: expected NAME:TYPE=VALUE")
    name, kind = name_kind.split(":", 1)
    coerced = _coerce(value, kind)
    return name, kind, coerced


def parse_flag(spec: str) -> tuple[str, str, object]:
    """Parse `--flag NAME:TYPE=DEFAULT` (e.g. NAME:int=0 or NAME:bool=true).

    For pure boolean toggles, pass `NAME:bool=true`. The flag's default
    value is what the script sees if the user does not provide one in
    WORKER_PARAMS.
    """
    if "=" not in spec:
        raise ValueError(f"bad --flag {spec!r}: expected NAME:TYPE=DEFAULT")
    name_kind, value = spec.split("=", 1)
    if ":" not in name_kind:
        raise ValueError(f"bad --flag {spec!r}: expected NAME:TYPE=DEFAULT")
    name, kind = name_kind.split(":", 1)
    coerced = _coerce(value, kind)
    return name, kind, coerced


def render_argv_body(
    params: list[tuple[str, str, object]],
    flags: list[tuple[str, str, object]],
) -> str:
    """Render the body of `build_argv()` for the template.

    Indentation: every emitted line lives INSIDE `def build_argv(...)`,
    so the base indent is 4 spaces. The function header is emitted by
    the template itself; we emit only the body.
    """
    lines: list[str] = []
    lines.append("grid_label = params.get('grid') or params.get('grid_label')")
    lines.append("if grid_label:")
    lines.append("    argv += ['--grid', str(grid_label)]")
    # params (value-based)
    for name, kind, value in params:
        if name == "grid":
            continue  # already handled
        flag = "--" + name.replace("_", "-")
        lines.append(f"if {name!r} in params:")
        lines.append(f"    argv += [{flag!r}, str(params[{name!r}])]")
        lines.append("else:")
        lines.append(f"    argv += [{flag!r}, {value!r}]")
    # flags: each flag has a kind and a default value (e.g. int 0 or bool True).
    for name, kind, default in flags:
        if name == "grid":
            continue
        flag = "--" + name.replace("_", "-")
        lines.append(f"if {name!r} in params:")
        lines.append(f"    argv += [{flag!r}, str(params[{name!r}])]")
        lines.append("else:")
        lines.append(f"    argv += [{flag!r}, {default!r}]")
    return "\n".join("    " + line for line in lines) if lines else "    pass"


def split_into_chunks(text: str, max_bytes: int) -> list[str]:
    """Split a script into <=max_bytes chunks aligned on line boundaries.

    Each chunk is wrapped in a syntactically valid .py envelope so the
    worker controller accepts the upload (it requires .py extension and
    may run a compile() check). The body of each chunk is encoded as a
    Python string literal via `repr()` — this guarantees the chunk is
    parseable regardless of what the original script contains (def, with,
    imports, even triple-quoted strings).
    """
    lines = text.splitlines(keepends=True)

    # Reserve bytes for envelope (header + footer + repr overhead).
    envelope_overhead = 200
    target = max(1024, max_bytes - envelope_overhead)

    raw_chunks: list[str] = []
    buf = ""
    for line in lines:
        if len(buf.encode("utf-8")) + len(line.encode("utf-8")) > target and buf:
            raw_chunks.append(buf)
            buf = ""
        buf += line
    if buf:
        raw_chunks.append(buf)

    n = len(raw_chunks)
    envelope_chunks: list[str] = []
    for i, body in enumerate(raw_chunks, start=1):
        envelope = (
            f"# === part {i}/{n} of "
            f"{os.environ.get('__SCAFFOLD_SCRIPT_NAME__', 'script.py')} ===\n"
            f"_part_{i} = {body!r}\n"
        )
        envelope_chunks.append(envelope)
    return envelope_chunks


def generate(
    script: Path,
    out_path: Path,
    name: str,
    param_specs: list[str],
    flag_specs: list[str],
    chunk_size: Optional[int],
) -> dict:
    text = script.read_text(encoding="utf-8")
    chunks: list[str]
    parts_repr: str
    if chunk_size and chunk_size > 0:
        os.environ["__SCAFFOLD_SCRIPT_NAME__"] = name
        raw_chunks = split_into_chunks(text, chunk_size)
        part_names = [f"{name}_p{i+1}.py" for i in range(len(raw_chunks))]
        chunks = raw_chunks
        parts_repr = repr(part_names)
        # also write the chunks next to the adapter so the user can upload them
        for fname, body in zip(part_names, raw_chunks):
            (out_path.parent / fname).write_text(body, encoding="utf-8")
    else:
        chunks = []
        parts_repr = "[]"

    parsed_params = [parse_param(p) for p in param_specs]
    parsed_flags = [parse_flag(f) for f in flag_specs]

    body = render_argv_body(parsed_params, parsed_flags)
    rendered = ADAPTER_TEMPLATE.format(
        entry_basename=name if name.endswith(".py") else f"{name}.py",
        chunks_repr=parts_repr,
        build_argv_body=body,
        worker_cwd=WORKER_CWD,
    )
    out_path.write_text(rendered, encoding="utf-8")
    return {
        "adapter": str(out_path),
        "chunks": [str(out_path.parent / n) for n in (parts_repr.strip("[]").replace("'", "").split(", ") if parts_repr != "[]" else [])],
        "size_bytes": out_path.stat().st_size,
    }


def main(argv: Optional[list[str]] = None) -> int:
    p = argparse.ArgumentParser(description="Generate an App-adapter for a script.")
    p.add_argument("script", type=Path, help="script to wrap")
    p.add_argument(
        "--name",
        default=None,
        help="entry filename on worker (default: <script_basename>_app.py)",
    )
    p.add_argument(
        "--out",
        type=Path,
        default=None,
        help="output path for adapter (default: <script_dir>/<name>.py)",
    )
    p.add_argument(
        "--param",
        action="append", default=[],
        help="parameter forwarded to the script: NAME:TYPE=VALUE (TYPE: str|int|float|bool)",
    )
    p.add_argument(
        "--flag",
        action="append", default=[],
        help="value-flag forwarded to the script: NAME:TYPE=DEFAULT (e.g. max_laps:int=0)",
    )
    p.add_argument(
        "--chunk-size",
        type=int, default=None,
        help="split the script into <=N-byte chunks before uploading (default: no split)",
    )
    args = p.parse_args(argv)

    if not args.script.exists():
        print(f"error: script not found: {args.script}", file=sys.stderr)
        return 1

    name = args.name or f"{args.script.stem}_app"
    if not name.endswith(".py"):
        name = name + ".py"
    out = args.out or args.script.parent / name

    info = generate(
        script=args.script,
        out_path=out,
        name=name,
        param_specs=args.param,
        flag_specs=args.flag,
        chunk_size=args.chunk_size,
    )
    print(json.dumps(info, indent=2))
    print(
        "\nNext steps:\n"
        f"  1. Review {info['adapter']}\n"
        f"  2. worker_cli.py upload --program <NAME_OR_UUID> {info['adapter']}"
        + (" " + " ".join(info["chunks"]) if info["chunks"] else "")
        + "\n"
        f"  3. worker_cli.py run --program <NAME_OR_UUID> --entry {name} --grid <LABEL> "
        "--params '{...}'\n"
        f"  4. worker_cli.py logs --program <NAME_OR_UUID> --follow 5",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())